
env:
  matrix:
    - CI_MODE=e2e
    - CI_MODE=js
    - CI_MODE=saucelabs_required



install:
  - ./scripts/ci/install.sh

script:
  - ./scripts/ci/build.sh
  - ./scripts/ci/test.sh
  - ./scripts/ci/angular.sh
  # all the scripts under this line will not quickly abort in case ${TRAVIS_TEST_RESULT} is 1 (job failure)
  - ./scripts/ci/cleanup.sh
  - ./scripts/ci/print-logs.sh
