language: node_js
sudo: false
node_js:
- '0.10'
env:
  global:
  - KARMA_BROWSERS=DartiumWithWebPlatform
  - E2E_BROWSERS=Dartium
  - LOGS_DIR=/tmp/angular-build/logs
  - ARCH=linux-x64
  matrix:
  - CHANNEL=stable
  - CHANNEL=dev

before_install:
- export DISPLAY=:99.0
- export GIT_SHA=$(git rev-parse HEAD)
- ./scripts/ci/init_android.sh
- ./scripts/ci/install_dart.sh
- sh -e /etc/init.d/xvfb start
- if [[ -e SKIP_TRAVIS_TESTS ]]; then { cat SKIP_TRAVIS_TESTS ; exit 0; } fi
before_script:
- mkdir -p $LOGS_DIR
script:
- ./scripts/ci/build.sh
- ./scripts/ci/test_unit.sh
- ./scripts/ci/test_e2e.sh
after_script:
- ./scripts/ci/print-logs.sh
