language: node_js
node_js:
- '0.10'
env:
  stable:
  - CHANNEL=stable
  - BROWSERS=DartiumWithWebPlatform
  - LOGS_DIR=/tmp/angular-build/logs

before_install:
- export DISPLAY=:99.0
- ./scripts/travis/install.sh
- sh -e /etc/init.d/xvfb start
- if [[ -e SKIP_TRAVIS_TESTS ]]; then { cat SKIP_TRAVIS_TESTS ; exit 0; } fi
before_script:
- mkdir -p $LOGS_DIR
script:
- ./scripts/travis/build.sh
after_script:
- ./scripts/travis/print-logs.sh