version: '3'
services:
  windows-env:
    build:
      context: ../../
      dockerfile: ./.buildkite/dockerfiles/windows-env.Dockerfile
  windows-test:
    build:
      context: ../../
      dockerfile: ./.buildkite/dockerfiles/windows-test.Dockerfile
      args:
        COMMIT_SHA: "${BUILDKITE_COMMIT}"
