name: angular2
version: 2.0.0-alpha.1
authors:
- Alex Eagle <alexeagle@google.com>
- Chirayu Krishnappa <chirayu@google.com>
- Jeff Cross <crossj@google.com>
- Misko Hevery <misko@google.com>
- Rado Kirov <radokirov@google.com>
- Tobias Bosch <tbosch@google.com>
- Victor Savkin <vsavkin@google.com>
- Yegor Jbanov <yjbanov@google.com>
description: Angular 2 for Dart - a web framework for modern web apps
homepage: https://github.com/angular/angular
environment:
  sdk: '>=1.4.0'
dependencies:
  stack_trace: '>=1.1.1 <2.0.0'
dev_dependencies:
  guinness: ">=0.1.16 <0.2.0"
