name: angular2
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: Angular 2 for Dart - a web framework for modern web apps
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.4.0'
dependencies:
  stack_trace: '>=1.1.1 <2.0.0'
dev_dependencies:
  guinness: ">=0.1.16 <0.2.0"
