steps:
  - label: windows-test
    plugins:
      - docker-compose#v2.6.0:
          build: windows-test
          config: .buildkite/dockerfiles/docker-compose.yml
    agents:
      windows: true
  - wait
  - label: windows-update-image
    branches: master
    plugins:
      - docker-compose#v2.6.0:
          push: windows-test:gcr.io/internal-200822/angular-windows:master
          config: .buildkite/dockerfiles/docker-compose.yml
    agents:
      windows: true
