name: benchmarks
environment:
  sdk: '>=1.4.0'
dependencies:
  facade:
    path: ../facade
  di:
    path: ../di
  reflection:
    path: ../reflection
  core:
    path: ../core
  change_detection:
    path: ../change_detection
  e2e_test_lib:
    path: ../e2e_test_lib
  browser: '>=0.10.0 <0.11.0'
transformers:
- $dart2js:
#    minify: false
    commandLineOptions: ['--dump-info', '--trust-type-annotations', '--trust-primitives']
