name: benchmarks
environment:
  sdk: '>=1.4.0'
dependencies:
  facade:
    path: ../facade
  di:
    path: ../di
  reflection:
    path: ../reflection
  core:
    path: ../core
  change_detection:
    path: ../change_detection
  benchpress:
    path: ../benchpress
  browser: '>=0.10.0 <0.11.0'
