name: forms
environment:
  sdk: '>=1.4.0'
dependencies:
  core:
    path: ../core
  di:
    path: ../di
  facade:
    path: ../facade
dev_dependencies:
  test_lib:
    path: ../test_lib
  guinness: ">=0.1.16 <0.2.0"
