name: examples
environment:
  sdk: '>=1.4.0'
dependencies:
  angular2:
    path: ../angular2
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  guinness: ">=0.1.16 <0.2.0"
transformers:
  - $dart2js:
      minify: true
      commandLineOptions: [--trust-type-annotations, --trust-primitives, --dump-info]
      #commandLineOptions: [--trust-type-annotations, --dump-info]
      #commandLineOptions: [--dump-info]
