name: examples
environment:
  sdk: '>=1.4.0'
dependencies:
  facade:
    path: ../facade
  core:
    path: ../core
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  test_lib:
    path: ../test_lib
  guinness: ">=0.1.16 <0.2.0"
