name: angular2_analyzer_plugin
version: 0.0.0
description: Dart analyzer plugin for Angular 2
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  angular2: '0.0.0'
  analyzer: '>=0.25.1 <0.27.0'
  plugin: "^0.1.0"
dev_dependencies:
  test_reflective_loader: '^0.0.3'
  typed_mock: '^0.0.4'
  unittest: '^0.11.0'
dependency_overrides:
  angular2:
    path: ../../dist/dart/angular2
