name: core
environment:
  sdk: '>=1.4.0'
dependencies:
  change_detection:
    path: ../change_detection
  di:
    path: ../di
  facade:
    path: ../facade
  reflection:
    path: ../reflection
dev_dependencies:
  test_lib:
    path: ../test_lib
  guinness: ">=0.1.16 <0.2.0"