name: http
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: Angular 2 Http Module
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  angular2: '^<%= packageJson.version %>'
dev_dependencies:
  guinness: '^0.1.17'
dependency_overrides:
  angular2:
    path: ../angular2
transformers:
- angular2
