name: Lock issues that are closed and inactive

on:
  schedule:
    # Run at the 20th minute of every hour
    - cron: '20 * * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@1e03b0d
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
          locks-per-execution: 250
